name: Monitor Kubernetes Pods

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск каждые 30 минут
  workflow_dispatch: # Запуск вручную

jobs:
  check-pods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        id: kubectl

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Get Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up SSH config
        run: |
          mkdir -p $HOME/.ssh
          echo "***\n***\n***" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "Host ec_bastion
                User jump_sa
                Port 32510
                HostName 178.124.206.53
                Host 192.168.201.* 192.168.202.* 192.168.203.* 192.168.208.*
                ProxyJump ec_bastion" > $HOME/.ssh/config
          chmod 600 $HOME/.ssh/config
        shell: /usr/bin/bash -e {0}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -v jump_sa@178.124.206.53 -p 32510
        continue-on-error: true

      - name: Set up SSH tunnel to bastion
        run: ssh -o StrictHostKeyChecking=no -f -N -L 6443:127.0.0.1:6443 jump_sa@178.124.206.53 -p 32510

      - name: Test Kubernetes connection
        run: kubectl cluster-info

      - name: Check pod status
        id: pod-status
        run: |
          set -e
          kubectl get pods --all-namespaces -o json > pods.json
          crashed_pods=$(jq '.items[] | select(.status.phase == "Failed" or .status.phase == "CrashLoopBackOff") | .metadata.name' pods.json)
          echo "crashed_pods=$crashed_pods" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        if: ${{ steps.pod-status.outputs.crashed_pods != '' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message
          custom_payload: |
            {
              "text": "Crashed/Failed Pods detected: ${{ steps.pod-status.outputs.crashed_pods }}",
              "username": "k8s-monitor",
              "icon_emoji": ":warning:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}