name: Hello GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JavaScript
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run hello script
        run: node hello.js
